# Generated by Django 5.2.1 on 2025-05-23 20:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_dailylist_shareable_alter_dailylist_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-order',), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.RemoveField(
            model_name='dailylist',
            name='updated',
        ),
        migrations.AddField(
            model_name='dailylist',
            name='effective_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dailylist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailylist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
