# Generated by Django 5.2.1 on 2025-05-25 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_options_remove_dailylist_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylist',
            options={'ordering': ('-created_dt',), 'verbose_name': 'daily list', 'verbose_name_plural': 'daily lists'},
        ),
        migrations.RenameField(
            model_name='dailylist',
            old_name='created',
            new_name='created_dt',
        ),
        migrations.RemoveField(
            model_name='dailylist',
            name='effective_date',
        ),
        migrations.AddField(
            model_name='dailylist',
            name='day_end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylist',
            name='locked_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylist',
            name='reference_timezone',
            field=models.CharField(default='America/Denver', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_timezone', models.CharField(default='America/Denver', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
